#!/usr/bin/env python3
"""
HAPI FHIR Container Manager

Unified CLI tool for managing HAPI FHIR Docker containers.
Wraps shell commands for ease of use with argument handling and instance tracking.
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional


class HapiInstanceRegistry:
    """Manages .env file with container instance registry"""
    
    ENV_FILE = Path(__file__).parent / ".env"
    
    @staticmethod
    def _load_instances() -> Dict[str, Dict[str, str]]:
        """
        Load instances from .env file.
        
        Returns:
            Dictionary mapping container name to instance info
            Example: {'my-hapi': {'port': '8081', 'data_dir': '/path', 'status': 'running'}}
        """
        instances = {}
        
        if not HapiInstanceRegistry.ENV_FILE.exists():
            return instances
        
        with open(HapiInstanceRegistry.ENV_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                # Skip empty lines and comments
                if not line or line.startswith('#'):
                    continue
                
                # Parse pipe-delimited format: NAME|PORT|DATA_DIR|STATUS
                parts = line.split('|')
                if len(parts) == 4:
                    name, port, data_dir, status = parts
                    instances[name] = {
                        'port': port,
                        'data_dir': data_dir,
                        'status': status
                    }
        
        return instances
    
    @staticmethod
    def _save_instances(*, instances: Dict[str, Dict[str, str]]) -> None:
        """
        Save instances to .env file.
        
        Args:
            instances: Dictionary mapping container name to instance info
        """
        # Ensure directory exists
        HapiInstanceRegistry.ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
        
        with open(HapiInstanceRegistry.ENV_FILE, 'w') as f:
            f.write("# HAPI FHIR Container Registry\n")
            f.write("# This file is auto-managed by hapi_manager.py\n")
            f.write("# Format: NAME|PORT|DATA_DIR|STATUS\n")
            f.write("#\n")
            f.write("# DO NOT edit this file manually - use hapi_manager.py commands\n")
            f.write("\n")
            
            for name, info in sorted(instances.items()):
                f.write(f"{name}|{info['port']}|{info['data_dir']}|{info['status']}\n")
    
    @staticmethod
    def add_instance(*, name: str, port: int, data_dir: str, status: str = 'running') -> None:
        """
        Add or update instance in registry.
        
        Args:
            name: Container name
            port: Port number
            data_dir: Data directory path
            status: Container status (default: 'running')
        """
        instances = HapiInstanceRegistry._load_instances()
        instances[name] = {
            'port': str(port),
            'data_dir': data_dir,
            'status': status
        }
        HapiInstanceRegistry._save_instances(instances=instances)
    
    @staticmethod
    def remove_instance(*, name: str) -> bool:
        """
        Remove instance from registry.
        
        Args:
            name: Container name
            
        Returns:
            True if instance was found and removed, False otherwise
        """
        instances = HapiInstanceRegistry._load_instances()
        
        if name not in instances:
            return False
        
        del instances[name]
        HapiInstanceRegistry._save_instances(instances=instances)
        return True
    
    @staticmethod
    def get_instance(*, name: str) -> Optional[Dict[str, str]]:
        """
        Get instance info by name.
        
        Args:
            name: Container name
            
        Returns:
            Instance info dictionary or None if not found
        """
        instances = HapiInstanceRegistry._load_instances()
        return instances.get(name)
    
    @staticmethod
    def check_port_conflict(*, port: int, exclude_name: str = None) -> bool:
        """
        Check if port is already used by another instance.
        
        Args:
            port: Port number to check
            exclude_name: Optional container name to exclude from check
            
        Returns:
            True if port is already in use (conflict), False otherwise
        """
        instances = HapiInstanceRegistry._load_instances()
        
        for name, info in instances.items():
            if exclude_name and name == exclude_name:
                continue
            if info['port'] == str(port):
                return True
        
        return False
    
    @staticmethod
    def get_all_instances() -> Dict[str, Dict[str, str]]:
        """
        Get all instances from registry.
        
        Returns:
            Dictionary of all instances
        """
        return HapiInstanceRegistry._load_instances()


class HapiManager:
    """Main HAPI FHIR container management class"""
    
    @staticmethod
    def run_docker(*, name: str, port: int, data_dir: str, ig_package: str = None) -> None:
        """
        Start or create HAPI FHIR container.
        
        Args:
            name: Container name
            port: Port to expose
            data_dir: Data directory path
            ig_package: Path to NDH IG package file (optional validation)
        """
        # Validate NDH IG package exists (required for system to function)
        if ig_package:
            ig_path = Path(ig_package)
            if not ig_path.exists():
                print()
                print("=" * 80)
                print("❌ ERROR: NDH Implementation Guide package not found")
                print("=" * 80)
                print(f"Expected location: {ig_path.absolute()}")
                print()
                print("The system requires the NDH IG package to function correctly.")
                print("Please either:")
                print("  1. Place ndh_package.tgz in the hload/ directory, or")
                print("  2. Specify the path using --ig-package /path/to/your/package.tgz")
                print()
                print("Download the NDH IG package from:")
                print("  https://build.fhir.org/ig/HL7/fhir-us-ndh/")
                print("=" * 80)
                sys.exit(1)
            print(f"✓ NDH IG package found: {ig_path.absolute()}")
        
        # Check for port conflicts with other tracked instances
        if HapiInstanceRegistry.check_port_conflict(port=port, exclude_name=name):
            conflicting_instances = [
                n for n, info in HapiInstanceRegistry.get_all_instances().items()
                if info['port'] == str(port) and n != name
            ]
            print(f"❌ Error: Port {port} is already in use by instance: {', '.join(conflicting_instances)}")
            print(f"   Please choose a different port or stop the conflicting instance.")
            sys.exit(1)
        
        # Convert to absolute path
        data_path = Path(data_dir).absolute()
        
        # Create _container_storage subdirectory
        storage_path = data_path / "_container_storage"
        print(f"📁 Creating storage directory: {storage_path}")
        storage_path.mkdir(parents=True, exist_ok=True)
        
        print(f"🚀 Starting HAPI FHIR container '{name}'...")
        print(f"   Port: {port}")
        print(f"   Data directory: {data_path}")
        print(f"   Storage path: {storage_path}")
        print()
        
        # Original run_hapi_docker.sh logic preserved as bash
        bash_script = f"""
CONTAINER_NAME="{name}"

# Check if container exists (running or stopped)
if docker ps -a --format '{{{{.Names}}}}' | grep -q "^${{CONTAINER_NAME}}$"; then
    echo "Container '${{CONTAINER_NAME}}' already exists. Starting it..."
    docker start ${{CONTAINER_NAME}}
    echo "Container '${{CONTAINER_NAME}}' started successfully."
else
    echo "Container '${{CONTAINER_NAME}}' does not exist. Creating and starting it..."
    docker run -d -p {port}:8080 \\
      --name ${{CONTAINER_NAME}} \\
      -v "{storage_path}:/data/hapi" \\
      -e HAPI_FHIR_ENFORCE_REFERENTIAL_INTEGRITY_ON_WRITE=false \\
      -e HAPI_FHIR_VALIDATE_ON_WRITE=false \\
      -e HAPI_FHIR_IG_RUNTIME_UPLOAD_ENABLED=true \\
      -e hapi.fhir.bulk_import_enabled=true \\
      hapiproject/hapi:latest
    
    if [ $? -eq 0 ]; then
        echo "✅ Container '${{CONTAINER_NAME}}' created and started successfully."
    else
        echo "❌ Failed to create container '${{CONTAINER_NAME}}'."
        exit 1
    fi
fi
"""
        
        result = subprocess.run(bash_script, shell=True, executable='/bin/bash')
        
        # Register instance in .env if successful
        if result.returncode == 0:
            HapiInstanceRegistry.add_instance(
                name=name,
                port=port,
                data_dir=str(data_path),
                status='running'
            )
            print()
            print(f"✅ Instance '{name}' registered in tracking registry.")
            print(f"   Server URL: http://localhost:{port}/fhir")
        else:
            print()
            print(f"❌ Failed to start container. Instance not registered.")
            sys.exit(1)
    
    @staticmethod
    def delete_docker(*, name: str, data_dir: str = None, remove_data: bool = False) -> None:
        """
        Delete HAPI FHIR container and optionally its data.
        
        Args:
            name: Container name
            data_dir: Data directory path (optional, retrieved from registry if not provided)
            remove_data: Whether to remove the data directory
        """
        # Get instance info from registry
        instance = HapiInstanceRegistry.get_instance(name=name)
        
        if not instance and not data_dir and remove_data:
            print(f"⚠️  Warning: Instance '{name}' not found in registry.")
            print(f"   Cannot remove data without --data-dir specified.")
            remove_data = False
        
        # Use registry data_dir if not provided
        if not data_dir and instance:
            data_dir = instance['data_dir']
        
        print(f"🗑️  Deleting HAPI FHIR container '{name}'...")
        
        # Original hard_delete_hapi_docker.sh logic preserved as bash
        bash_script = f"""
echo "Stopping HAPI FHIR container ({name})..."
docker stop {name} 2>&1

echo "Removing HAPI FHIR container ({name})..."
docker rm {name} 2>&1

echo "Container {name} has been deleted."
"""
        
        subprocess.run(bash_script, shell=True, executable='/bin/bash')
        
        # Remove from registry
        if HapiInstanceRegistry.remove_instance(name=name):
            print(f"✅ Instance '{name}' removed from tracking registry.")
        else:
            print(f"⚠️  Instance '{name}' was not in tracking registry.")
        
        # Handle data directory removal if requested
        if remove_data and data_dir:
            data_path = Path(data_dir)
            
            if not data_path.exists():
                print(f"⚠️  Data directory does not exist: {data_path}")
                return
            
            # Confirmation prompt
            print()
            print(f"⚠️  WARNING: About to permanently delete data directory:")
            print(f"   {data_path}")
            print()
            response = input("   Type 'DELETE' to confirm: ")
            
            if response == 'DELETE':
                import shutil
                print(f"🗑️  Removing data directory...")
                shutil.rmtree(data_path)
                print(f"✅ Data directory removed: {data_path}")
            else:
                print(f"❌ Deletion cancelled. Data directory preserved.")
    
    @staticmethod
    def load_ig(*, ig_file: str, name: str = None, port: int = None) -> None:
        """
        Upload implementation guide to HAPI server.
        
        Args:
            ig_file: Path to IG package file (.tgz)
            name: Container name (port will be looked up from registry)
            port: Port number (if not using --name)
        """
        # Check if IG file exists
        ig_path = Path(ig_file)
        if not ig_path.exists():
            print(f"❌ Error: IG file not found: {ig_file}")
            sys.exit(1)
        
        # Determine port
        if name:
            instance = HapiInstanceRegistry.get_instance(name=name)
            if not instance:
                print(f"❌ Error: Instance '{name}' not found in registry.")
                print(f"   Use --port instead, or run 'list' to see available instances.")
                sys.exit(1)
            port = int(instance['port'])
            print(f"📋 Loading IG from '{ig_file}' to instance '{name}' on port {port}...")
        elif port:
            print(f"📋 Loading IG from '{ig_file}' to port {port}...")
        else:
            print(f"❌ Error: Must specify either --name or --port")
            sys.exit(1)
        
        # Create temp file for base64 encoding in same directory as IG file
        temp_b64 = ig_path.parent / f"{ig_path.stem}_temp.b64"
        
        # Original load_ig.sh logic - EXACTLY as it was, with configurable port and file path
        # NOTE: The heredoc must NOT have quotes around EOF for variable substitution to work
        bash_script = f"""
base64 < "{ig_path.absolute()}" | tr -d '\\n' > "{temp_b64}" && \\
curl -i -X POST \\
  -H "Content-Type: application/fhir+json" \\
  --data-binary @- \\
  'http://localhost:{port}/fhir/ImplementationGuide/$install' <<EOF
{{
  "resourceType": "Parameters",
  "parameter": [
    {{
      "name": "npmContent",
      "valueBase64Binary": "$(cat "{temp_b64}")"
    }}
  ]
}}
EOF

# Clean up temp file
rm -f "{temp_b64}"
"""
        
        result = subprocess.run(bash_script, shell=True, executable='/bin/bash', 
                               capture_output=True, text=True)
        
        # Check for HTTP errors in the output (curl returns 0 even on HTTP 4xx/5xx)
        output = result.stdout + result.stderr
        
        # Look for HTTP error status codes
        has_error = False
        if 'HTTP/1.1 4' in output or 'HTTP/1.1 5' in output:
            has_error = True
        
        # Print the output
        if output:
            print(output)
        
        if result.returncode != 0 or has_error:
            print()
            print(f"❌ Failed to load implementation guide.")
            sys.exit(1)
        else:
            print()
            print(f"✅ Implementation guide loaded successfully.")
    
    @staticmethod
    def bulk_import(*, source_dir: str, name: str = None, port: int = None, **kwargs) -> None:
        """
        Bulk import NDJSON files using existing bulk_import_loader.py.
        
        Args:
            source_dir: Directory containing NDJSON files
            name: Container name (port will be looked up from registry)
            port: Port number (if not using --name)
            **kwargs: Additional arguments to pass to bulk_import_loader.py
        """
        # Determine port and construct target URL
        if name:
            instance = HapiInstanceRegistry.get_instance(name=name)
            if not instance:
                print(f"❌ Error: Instance '{name}' not found in registry.")
                print(f"   Use --port instead, or run 'list' to see available instances.")
                sys.exit(1)
            port = int(instance['port'])
            print(f"📦 Bulk importing to instance '{name}' on port {port}...")
        elif port:
            print(f"📦 Bulk importing to port {port}...")
        else:
            print(f"❌ Error: Must specify either --name or --port")
            sys.exit(1)
        
        target_url = f"http://localhost:{port}/fhir"
        
        # Build command for bulk_import_loader.py
        bulk_loader_path = Path(__file__).parent / "bulk_import_loader.py"
        
        cmd = [
            sys.executable,
            str(bulk_loader_path),
            source_dir,
            "--target-url", target_url
        ]
        
        # Add optional arguments
        if kwargs.get('verbose'):
            cmd.append('--verbose')
        if kwargs.get('no_cleanup'):
            cmd.append('--no-cleanup')
        if kwargs.get('continue_on_error'):
            cmd.append('--continue-on-error')
        if kwargs.get('cli_path'):
            cmd.extend(['--cli-path', kwargs['cli_path']])
        if kwargs.get('batch_size') is not None:
            cmd.extend(['--batch-size', str(kwargs['batch_size'])])
        
        print(f"🔧 Running: {' '.join(cmd)}")
        print()
        
        result = subprocess.run(cmd)
        sys.exit(result.returncode)
    
    @staticmethod
    def list_instances() -> None:
        """List all tracked instances"""
        instances = HapiInstanceRegistry.get_all_instances()
        
        if not instances:
            print("No instances tracked in registry.")
            print()
            print("💡 Use 'run' command to create a new instance.")
            return
        
        print("=" * 100)
        print("TRACKED HAPI FHIR INSTANCES")
        print("=" * 100)
        print(f"{'NAME':<25} {'PORT':<8} {'STATUS':<12} {'DATA_DIR'}")
        print("-" * 100)
        
        for name, info in sorted(instances.items()):
            print(f"{name:<25} {info['port']:<8} {info['status']:<12} {info['data_dir']}")
        
        print("=" * 100)
        print(f"Total: {len(instances)} instance(s)")
        print()
        print("💡 Use 'info --name <name>' for detailed information about an instance.")
    
    @staticmethod
    def info_instance(*, name: str) -> None:
        """
        Show detailed info about specific instance.
        
        Args:
            name: Container name
        """
        instance = HapiInstanceRegistry.get_instance(name=name)
        
        if not instance:
            print(f"❌ Instance '{name}' not found in registry.")
            print()
            print("💡 Use 'list' command to see all tracked instances.")
            sys.exit(1)
        
        print("=" * 80)
        print(f"INSTANCE: {name}")
        print("=" * 80)
        print(f"Port:            {instance['port']}")
        print(f"Status:          {instance['status']}")
        print(f"Data Directory:  {instance['data_dir']}")
        print(f"Storage Path:    {instance['data_dir']}/_container_storage")
        print(f"Server URL:      http://localhost:{instance['port']}/fhir")
        print("=" * 80)
        
        # Check actual Docker container status
        print()
        print("🔍 Checking Docker container status...")
        bash_script = f"""
if docker ps --format '{{{{.Names}}}}' | grep -q "^{name}$"; then
    echo "✅ Container is currently RUNNING"
    docker ps --filter name=^{name}$ --format "   Started: {{{{.Status}}}}"
elif docker ps -a --format '{{{{.Names}}}}' | grep -q "^{name}$"; then
    echo "⚠️  Container exists but is STOPPED"
    docker ps -a --filter name=^{name}$ --format "   Status: {{{{.Status}}}}"
else
    echo "❌ Container does not exist in Docker"
fi
"""
        subprocess.run(bash_script, shell=True, executable='/bin/bash')


def main():
    """Main entry point for command-line execution."""
    parser = argparse.ArgumentParser(
        description="HAPI FHIR Container Manager - Unified tool for managing HAPI FHIR Docker containers",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Create and start a new instance
  %(prog)s run --name my-hapi --port 8081 --data-dir /path/to/storage
  
  # List all tracked instances
  %(prog)s list
  
  # Get info about specific instance
  %(prog)s info --name my-hapi
  
  # Load implementation guide
  %(prog)s load-ig ./ndh_package.tgz --name my-hapi
  
  # Bulk import NDJSON files
  %(prog)s bulk-import /path/to/ndjson --name my-hapi
  
  # Delete instance (keeps data)
  %(prog)s delete --name my-hapi
  
  # Delete instance and remove all data
  %(prog)s delete --name my-hapi --remove-data
        """
    )
    
    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    
    # run subcommand
    run_parser = subparsers.add_parser(
        'run',
        help='Start or create HAPI FHIR container',
        description='Create a new HAPI FHIR container or start an existing one'
    )
    run_parser.add_argument(
        '--name',
        required=True,
        help='Container name (must be unique)'
    )
    run_parser.add_argument(
        '--port',
        required=True,
        type=int,
        help='Port to expose (must be unique, user must be aware of conflicts)'
    )
    run_parser.add_argument(
        '--data-dir',
        required=True,
        help='Data directory path (can be relative or absolute)'
    )
    run_parser.add_argument(
        '--ig-package',
        default=str(Path(__file__).parent / 'ndh_package.tgz'),
        help='Path to NDH IG package file (default: hload/ndh_package.tgz)'
    )
    
    # delete subcommand
    del_parser = subparsers.add_parser(
        'delete',
        help='Delete HAPI FHIR container',
        description='Stop and remove a HAPI FHIR container, optionally removing its data'
    )
    del_parser.add_argument(
        '--name',
        required=True,
        help='Container name'
    )
    del_parser.add_argument(
        '--data-dir',
        help='Data directory (optional, retrieved from registry if not provided)'
    )
    del_parser.add_argument(
        '--remove-data',
        action='store_true',
        help='Remove data directory (requires confirmation)'
    )
    
    # load-ig subcommand
    ig_parser = subparsers.add_parser(
        'load-ig',
        help='Load implementation guide',
        description='Upload an implementation guide package to the HAPI server'
    )
    ig_parser.add_argument(
        'ig_file',
        help='Path to IG package file (.tgz)'
    )
    ig_group = ig_parser.add_mutually_exclusive_group(required=True)
    ig_group.add_argument(
        '--name',
        help='Container name (port will be looked up from registry)'
    )
    ig_group.add_argument(
        '--port',
        type=int,
        help='Port number (if not using --name)'
    )
    
    # bulk-import subcommand
    bulk_parser = subparsers.add_parser(
        'bulk-import',
        help='Bulk import NDJSON files',
        description='Import NDJSON files into HAPI FHIR server using hapi-fhir-cli'
    )
    bulk_parser.add_argument(
        'source_dir',
        help='Directory containing NDJSON files'
    )
    bulk_group = bulk_parser.add_mutually_exclusive_group(required=True)
    bulk_group.add_argument(
        '--name',
        help='Container name (port will be looked up from registry)'
    )
    bulk_group.add_argument(
        '--port',
        type=int,
        help='Port number (if not using --name)'
    )
    bulk_parser.add_argument(
        '--cli-path',
        default='hapi-fhir-cli',
        help='Path to hapi-fhir-cli executable (default: hapi-fhir-cli in PATH)'
    )
    bulk_parser.add_argument(
        '--batch-size',
        type=int,
        help='Batch size for processing resources (default: hapi-fhir-cli default)'
    )
    bulk_parser.add_argument(
        '--verbose',
        action='store_true',
        help='Enable verbose logging'
    )
    bulk_parser.add_argument(
        '--no-cleanup',
        action='store_true',
        help='Keep temporary directories for debugging'
    )
    bulk_parser.add_argument(
        '--continue-on-error',
        action='store_true',
        help='Continue loading even if a resource fails'
    )
    
    # list subcommand
    list_parser = subparsers.add_parser(
        'list',
        help='List all tracked instances',
        description='Show all HAPI FHIR instances tracked in the registry'
    )
    
    # info subcommand
    info_parser = subparsers.add_parser(
        'info',
        help='Show instance details',
        description='Display detailed information about a specific instance'
    )
    info_parser.add_argument(
        '--name',
        required=True,
        help='Container name'
    )
    
    # Parse arguments
    args = parser.parse_args()
    
    # Show help if no command specified
    if not args.command:
        parser.print_help()
        sys.exit(0)
    
    # Dispatch to appropriate method
    try:
        if args.command == 'run':
            HapiManager.run_docker(
                name=args.name,
                port=args.port,
                data_dir=args.data_dir,
                ig_package=args.ig_package
            )
        elif args.command == 'delete':
            HapiManager.delete_docker(
                name=args.name,
                data_dir=args.data_dir,
                remove_data=args.remove_data
            )
        elif args.command == 'load-ig':
            HapiManager.load_ig(
                ig_file=args.ig_file,
                name=args.name,
                port=args.port
            )
        elif args.command == 'bulk-import':
            HapiManager.bulk_import(
                source_dir=args.source_dir,
                name=args.name,
                port=args.port,
                cli_path=args.cli_path,
                batch_size=args.batch_size,
                verbose=args.verbose,
                no_cleanup=args.no_cleanup,
                continue_on_error=args.continue_on_error
            )
        elif args.command == 'list':
            HapiManager.list_instances()
        elif args.command == 'info':
            HapiManager.info_instance(name=args.name)
        else:
            parser.print_help()
            sys.exit(1)
    
    except KeyboardInterrupt:
        print("\n\n⚠️  Operation cancelled by user.")
        sys.exit(130)
    except Exception as error:
        print(f"\n❌ Fatal error: {error}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
